# AI Label Assist Configuration
# This YAML file contains all URLs and settings for the app.
# You can edit this file manually or via the app's settings menu.

# API endpoints
# api_url: "https://si0vmc0854.de.bosch.com/swap-prod/api/ubk-keywords"
api_url: "http://localhost:3030/posts"

# Window URLs
main_window_url: "/index.html"
# splashscreen_url: "/splashscreen.html"  # Removed, file no longer exists
settings_url: "/settings.html"

# Other settings
window:
  width: 600
  height: 400
  position: right-bottom

# Add more settings as needed
